-- =============================================================
-- ExpansionIQ: Retail Expansion Strategy for Minimalist
-- SQL Business Analysis
-- =============================================================

SELECT * FROM cities;
SELECT * FROM customers;
SELECT * FROM products;
SELECT * FROM orders;
SELECT * FROM order_items;

-- =============================================================
-- Reports & Data Analysis
-- =============================================================

-- Q1. Total Revenue
-- What is the total revenue generated by Minimalist across India?

SELECT
SUM(quantity * selling_price) AS total_revenue
FROM order_items;

-- =============================================================

-- Q2. Revenue by City
-- Which cities generate the highest revenue?

SELECT
c.city,
ROUND(SUM(oi.quantity * oi.selling_price),2) AS total_revenue
FROM orders o
JOIN customers c
ON o.customer_id = c.customer_id
JOIN order_items oi
ON o.order_id = oi.order_id
GROUP BY 1
ORDER BY 2 DESC;

-- =============================================================

-- Q3. Monthly Revenue Trend
-- How has revenue changed month-over-month?

SELECT
EXTRACT(YEAR FROM o.order_date) AS year,
EXTRACT(MONTH FROM o.order_date) AS month,
ROUND(SUM(oi.quantity * oi.selling_price),2) AS revenue
FROM orders o
JOIN order_items oi
ON o.order_id = oi.order_id
GROUP BY 1,2
ORDER BY 1,2;

-- =============================================================

-- Q4. Revenue by Product Category
-- Which skincare categories contribute the most revenue?

SELECT
p.category,
ROUND(SUM(oi.quantity * oi.selling_price),2) AS revenue
FROM order_items oi
JOIN products p
ON oi.product_id = p.product_id
GROUP BY 1
ORDER BY 2 DESC;

-- =============================================================

-- Q5. Top Selling Products
-- Which are the top 10 products based on sales volume?

SELECT
p.product_name,
SUM(oi.quantity) AS units_sold
FROM order_items oi
JOIN products p
ON oi.product_id = p.product_id
GROUP BY 1
ORDER BY 2 DESC
LIMIT 10;

-- =============================================================

-- Q6. Average Order Value by City
-- What is the average order value in each city?

SELECT
c.city,
ROUND(
SUM(oi.quantity*oi.selling_price)
/COUNT(DISTINCT o.order_id),2) AS avg_order_value
FROM orders o
JOIN customers c
ON o.customer_id = c.customer_id
JOIN order_items oi
ON oi.order_id = o.order_id
GROUP BY 1
ORDER BY 2 DESC;

-- =============================================================

-- Q7. Customer Lifetime Value (CLV)

SELECT
c.customer_id,
c.name,
ROUND(SUM(oi.quantity*oi.selling_price),2) AS customer_lifetime_value
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
JOIN order_items oi
ON o.order_id = oi.order_id
GROUP BY 1,2
ORDER BY 3 DESC
LIMIT 20;

-- =============================================================

-- Q8. Repeat Purchase Analysis

WITH repeat_customers AS
(
SELECT
customer_id,
COUNT(order_id) AS total_orders
FROM orders
GROUP BY 1
HAVING COUNT(order_id)>1
)

SELECT
c.city,
COUNT(r.customer_id) AS repeat_customers
FROM repeat_customers r
JOIN customers c
ON r.customer_id = c.customer_id
GROUP BY 1
ORDER BY 2 DESC;

-- =============================================================

-- Q9. Top Products by City

SELECT *
FROM
(
SELECT
c.city,
p.product_name,
SUM(oi.quantity) AS units_sold,
DENSE_RANK() OVER(
PARTITION BY c.city
ORDER BY SUM(oi.quantity) DESC
) AS ranking
FROM customers c
JOIN orders o
ON c.customer_id=o.customer_id
JOIN order_items oi
ON o.order_id=oi.order_id
JOIN products p
ON oi.product_id=p.product_id
GROUP BY 1,2
)t
WHERE ranking<=3;

-- =============================================================

-- Q10. Market Potential Analysis

SELECT
ci.city,
SUM(oi.quantity*oi.selling_price) AS revenue,
COUNT(DISTINCT c.customer_id) AS customers,
ci.population,
ci.average_income,
ci.competition_score,
ci.rent_index
FROM cities ci
JOIN customers c
ON ci.city=c.city
JOIN orders o
ON c.customer_id=o.customer_id
JOIN order_items oi
ON o.order_id=oi.order_id
GROUP BY 1,4,5,6,7
ORDER BY revenue DESC;

/*
Recommendation

1. Bengaluru
• Highest revenue
• Highest CLV
• Strong customer density
• High projected ROI

2. Hyderabad
• High repeat purchase rate
• Growing skincare demand
• Moderate competition

3. Pune
• High average order value
• Lower operational costs
• Excellent market potential

4. Ahmedabad
• Fast-growing customer base
• Low rent index
• Strong expansion opportunity

5. Jaipur
• Emerging market
• Increasing online demand
• Cost-effective store operations
*/
